@echo off
echo Starting LLM Council Frontend...
cd frontend

echo Checking dependencies...
if not exist "node_modules" (
    echo Installing all dependencies...
    npm install
) else (
    echo Verifying critical dependencies...
    npm list html2canvas >nul 2>&1
    if errorlevel 1 (
        echo Missing critical dependencies, reinstalling...
        npm install
    ) else (
        echo Dependencies OK, checking for updates...
        npm install --silent
    )
)

echo.
echo Starting development server...
npm run dev